---
version: '2'

services:

  # games
  factorio:
    container_name: factorio
    image: dtandersen/factorio
    network_mode: host
    privileged: true
    ports:
      - 34197:34197/tcp
      - 27015:27015/tcp
    volumes:
      - /mnt/main/factorio:/factorio

  # 3d printing
  octoprint:
    container_name: octoprint
    image: octoprint/octoprint
    network_mode: host
    privileged: true
    volumes:
      - /mnt/main/octoprint/config:/home/octoprint/.octoprint
      - /mnt/main/octoprint/venv:/opt/octoprint/venv
      - /dev:/dev
    ports:
      - 5000:5000
    environment:
      - TZ=America/Los_Angeles
      - UID=0
      - GID=0

  # front end
  htpcmanager:
    container_name: htpcmanager
    image: linuxserver/htpcmanager
    network_mode: host
    privileged: true
    volumes:
      - /mnt/main/htpcmanager/config:/config
    environment:
      - TZ=America/Los_Angeles
      - PUID=0
      - PGID=0

  # media
  plex:
    container_name: plex
    image: plexinc/pms-docker:plexpass
    network_mode: host
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      PLEX_CLAIM: ${PLEX_CLAIM}
    volumes:
      - /dev/shm:/dev/shm
      - /mnt/main/plex/config:/config:rw
      - /mnt/main/plex/transcode:/transcode:rw
      - /mnt/main:/data:rw

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    network_mode: host
    restart: always
    ports:
      - 9117:9117
    environment:
      TZ: ${TZ}
      PUID: 0
      PGID: 0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/main/sonarr/config:/config
      - /mnt/main/transmission_tv/downloads:/data/completed
      - /mnt/main/sabnzbd/downloads:/downloads
      - /mnt/main/sabnzbd/incomplete-downloads:/incomplete-downloads
      - /mnt/main/tv:/tv

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    network_mode: host
    restart: always
    ports:
      - 7878:7878
    environment:
      - TZ=${TZ}
      - PUID=0
      - PGID=0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/main/radarr/config:/config
      - /mnt/main/transmission_movies/downloads:/data/completed
      - /mnt/main/transmission_movies/home/torrents:/torrents
      - /mnt/main/movies:/movies
      - /mnt/main/sabnzbd/downloads:/downloads
      - /mnt/main/sabnzbd/incomplete-downloads:/incomplete-downloads

  # indexers
  hydra:
    container_name: hydra
    image: linuxserver/hydra
    network_mode: host
    restart: always
    ports:
      - 5075:5075
    environment:
      TZ: ${TZ}
      PUID: 0
      PGID: 0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/main/hydra/config:/config
      - /mnt/main/hydra/downloads:/downloads
  jackett:
    container_name: jackett
    image: linuxserver/jackett
    network_mode: host
    restart: always
    ports:
      - 8989:8989
    environment:
      - TZ=${TZ}
      - PUID=0
      - PGID=0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/main/jackett/config:/config

  # downloaders
  transmission_movies:
    container_name: transmission_movies
    image: haugene/transmission-openvpn
    restart: always
    privileged: true
    ports:
      - 9091:9091
    environment:
      TZ: ${TZ}
      OPENVPN_PROVIDER: ${OPENVPN_PROVIDER}
      OPENVPN_CONFIG: ${OPENVPN_CONFIG}
      OPENVPN_USERNAME: ${OPENVPN_USERNAME}
      OPENVPN_PASSWORD: ${OPENVPN_PASSWORD}
      OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60
      TRANSMISSION_BLOCKLIST_ENABLED: true
      TRANSMISSION_BLOCKLIST_URL: http://john.bitsurge.net/public/biglist.p2p.gz
      TRANSMISSION_DHT_ENABLED: false
      LOCAL_NETWORK: 10.1.0.0/24
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/main/movies:/mnt/main/movies
      - /mnt/main/transmission_movies/downloads:/data/completed
      - /mnt/main/transmission_movies/incomplete:/data/incomplete
      - /mnt/main/transmission_movies/home:/data/transmission-home
      - /mnt/main/transmission_movies/config:/var/db/transmission

  transmission_tv:
    container_name: transmission_tv
    image: haugene/transmission-openvpn
    restart: always
    privileged: true
    ports:
      - 9092:9091
    environment:
      TZ: ${TZ}
      OPENVPN_PROVIDER: ${OPENVPN_PROVIDER}
      OPENVPN_CONFIG: ${OPENVPN_CONFIG}
      OPENVPN_USERNAME: ${OPENVPN_USERNAME}
      OPENVPN_PASSWORD: ${OPENVPN_PASSWORD}
      OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60
      TRANSMISSION_BLOCKLIST_ENABLED: true
      TRANSMISSION_BLOCKLIST_URL: http://john.bitsurge.net/public/biglist.p2p.gz
      TRANSMISSION_DHT_ENABLED: false
      LOCAL_NETWORK: 10.1.0.0/24
      # saved for testing
      # TRANSMISSION_RATIO_LIMIT_ENABLED: true
      # TRANSMISSION_RATIO_LIMIT: 0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/main/transmission_tv/incomplete:/data/incomplete
      - /mnt/main/transmission_tv/downloads:/data/completed
      - /mnt/main/transmission_tv/home:/data/transmission-home
      - /mnt/main/transmission_tv/config:/var/db/transmission

  sab:
    container_name: sab
    image: binhex/arch-sabnzbdvpn
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - 8080:8080
      - 8090:8090
      - 8118:8118
    environment:
      - VPN_ENABLED=yes
      - VPN_USER=${OPENVPN_USERNAME}
      - VPN_PASS=${OPENVPN_PASSWORD}
      - VPN_PROV=pia
      - VPN_REMOTE=${OPENVPN_REMOTE}
      - STRICT_PORT_FORWARD=no
      - ENABLE_PRIVOXY=yes
      - LAN_NETWORK=10.1.0.0/24
      - NAME_SERVERS=209.222.18.222,37.235.1.174,8.8.8.8,209.222.18.218,37.235.1.177,8.8.4.4
      - ADDITIONAL_PORTS=8081
      - DEBUG=false
      - UMASK=000
      - TZ=${TZ}
      - PUID=0
      - PGID=0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/main/openvpn:/config/openvpn
      - /mnt/main/sabnzbd/config:/config
      - /mnt/main/sabnzbd/downloads:/downloads
      - /mnt/main/sabnzbd/incomplete-downloads:/incomplete-downloads

  # services
  samba:
    container_name: samba
    image: joebiellik/samba-server
    network_mode: host
    privileged: true
    volumes:
      - /mnt/main/samba/config:/config
      - /mnt/main/tv:/mnt/tv
      - /mnt/main/movies:/mnt/movies
      - /mnt/main/music:/mnt/music
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    environment:
      - USERNAME=${SAMBA_USER}
      - PASSWORD=${SAMBA_PASS}

  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - /mnt/main/mysql/data:/var/lib/mysql
